### ISSUE TITLE
Some one knows where I can find the darjeeling-prack-1.8, a PRACK message implementation made by Olle E. Johansson? thanks.

### ISSUE THREAD

**Issue by antonio-couto** [InterLinked1/chan_sip#1]
Some one knows where I can find the darjeeling-prack-1.8, a PRACK message implementation made by Olle E. Johansson? thanks.

**Comment by InterLinked1** [comment]
> Some one knows where I can find the darjeeling-prack-1.8, a PRACK message implementation made by Olle E. Johansson? thanks.

What does this patch actually do? I presume it's the one mentioned in this commit? If so, it sounds like the patch is obsolete, superseded by functionality merged into Asterisk quite a while ago.

```
2012-11-20 16:45 +0000 [r376521]  Mark Michelson <mmichelson@digium.com>

	* channels/sip/include/sip.h, channels/chan_sip.c: Add "Require:
	  timer" to 200 OK responses when appropriate. The method by which
	  the Require header is added to 200 responses is inspired by the
	  method that Olle Johansson uses in his darjeeling-prack branch.
	  (closes issue ASTERISK-20570) Reported by Matt Jordan, at the
	  behest of Olle Johansson Review:
	  https://reviewboard.asterisk.org/r/2172
```

https://issues-archive.asterisk.org/ASTERISK-20570
